MOUSEKEY_ENABLE     = no      # Mouse keys
#RGBLIGHT_ENABLE     = yes     # Enable WS2812 RGB underlight.
RGB_MATRIX_ENABLE   = yes		  # Enable RGB matrix
RGB_MATRIX_DRIVER   = WS2812    # Enable WS2812 for RGB Matrix
VIA_ENABLE          = yes     # Enable VIA
VIAL_ENABLE         = yes     # Enable VIAL
RAW_ENABLE          = yes 	  # Enable RAW HID
OLED_ENABLE         = no
#OLED_DRIVER         = SSD1306
EXTRAKEY_ENABLE     = yes
LTO_ENABLE          = yes
QMK_SETTINGS        = no
COMBO_ENABLE        = no
#CONVERT_TO			= kb2040
ENCODER_ENABLE = yes        # Activate Encoder
ENCODER_MAP_ENABLE = yes
